services:
  postgres:
    container_name: postgres
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always

  redis:
    image: redis:5.0.7-alpine
    ports:
      - "6379:6379"

  dashboard:
    image: dataesr/dashboard-crawler:1.0
    ports:
      - "9181:9181"
    command: rq-dashboard -H redis
    depends_on:
      - redis

  worker:
    image: dataesr/bso3-harvest-publication:latest_local
    privileged: true
    command: bash -c "sleep 10 && python3 manage.py run_worker"
    environment:
      - PUBLICATIONS_DUMP_BUCKET=${PUBLICATIONS_DUMP_BUCKET}

      # swift
      - OS_USERNAME=${OS_USERNAME}
      - OS_PASSWORD=${OS_PASSWORD}
      - OS_USER_DOMAIN_NAME=${OS_USER_DOMAIN_NAME}
      - OS_PROJECT_DOMAIN_NAME=${OS_PROJECT_DOMAIN_NAME}
      - OS_PROJECT_NAME=${OS_PROJECT_NAME}
      - OS_PROJECT_ID=${OS_PROJECT_ID}
      - OS_REGION_NAME=${OS_REGION_NAME}
      - OS_AUTH_URL=${OS_AUTH_URL}
      - OS_TENANT_NAME=${OS_TENANT_NAME}
      - OS_TENANT_ID=${OS_TENANT_ID}

      # Postgres database
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}

      # Wiley
      - WILEY_TOKEN=${WILEY_TOKEN}
      - WILEY_EZPROXY_USER=${WILEY_EZPROXY_USER}
      - WILEY_EZPROXY_PASS=${WILEY_EZPROXY_PASS}
      - WILEY_PUBLICATION_URL=${WILEY_PUBLICATION_URL}
      - WILEY_BASE_URL=${WILEY_BASE_URL}
    depends_on:
      - redis
      - postgres
    restart: always


  web:
    image: dataesr/bso3-harvest-publication:latest_local
    privileged: true
    ports:
      - "5004:5000"
    command: bash -c "sleep 10 && python3 manage.py run -h 0.0.0.0"
    environment:
      - PUBLICATIONS_DUMP_BUCKET=${PUBLICATIONS_DUMP_BUCKET}

      # swift
      - OS_USERNAME=${OS_USERNAME}
      - OS_PASSWORD=${OS_PASSWORD}
      - OS_USER_DOMAIN_NAME=${OS_USER_DOMAIN_NAME}
      - OS_PROJECT_DOMAIN_NAME=${OS_PROJECT_DOMAIN_NAME}
      - OS_PROJECT_NAME=${OS_PROJECT_NAME}
      - OS_PROJECT_ID=${OS_PROJECT_ID}
      - OS_REGION_NAME=${OS_REGION_NAME}
      - OS_AUTH_URL=${OS_AUTH_URL}
      - OS_TENANT_NAME=${OS_TENANT_NAME}
      - OS_TENANT_ID=${OS_TENANT_ID}

      # Postgres database
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}

      # Wiley
      - WILEY_TOKEN=${WILEY_TOKEN}
      - WILEY_EZPROXY_USER=${WILEY_EZPROXY_USER}
      - WILEY_EZPROXY_PASS=${WILEY_EZPROXY_PASS}
      - WILEY_PUBLICATION_URL=${WILEY_PUBLICATION_URL}
      - WILEY_BASE_URL=${WILEY_BASE_URL}
    depends_on:
      - worker
    restart: always


volumes:
  bso3-harvest-publication:

