services:
  postgres:
    container_name: postgres
    image: postgres:12.0-alpine
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    restart: always

  redis:
    image: redis:5.0.7-alpine
    ports:
      - "6379:6379"

  dashboard:
    image: dataesr/dashboard-crawler:1.0
    ports:
      - "9181:9181"
    command: rq-dashboard -H redis
    depends_on:
      - redis

  worker:
    build: 
      context: .
      dockerfile: ./Dockerfiles/dev/Dockerfile
    volumes:
      - .:/src
    privileged: true
    command: bash -c "sleep 10 && python3 manage.py run_worker"
    environment:
      # Postgres database
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      # Elsevier
      - ELSEVIER_APIKEY=${ELSEVIER_APIKEY}
      - ELSEVIER_INSTTOKEN=${ELSEVIER_INSTTOKEN}
      - ELSEVIER_PUBLICATION_URL=${ELSEVIER_PUBLICATION_URL}
      # Swift
      - AUTH_VERSION=${AUTH_VERSION}
      - OS_AUTH_URL=${OS_AUTH_URL}
      - OS_PASSWORD=${OS_PASSWORD}
      - OS_PROJECT_DOMAIN_NAME=${OS_PROJECT_DOMAIN_NAME}
      - OS_PROJECT_ID=${OS_PROJECT_ID}
      - OS_PROJECT_NAME=${OS_PROJECT_NAME}
      - OS_REGION_NAME=${OS_REGION_NAME}
      - OS_TENANT_ID=${OS_TENANT_ID}
      - OS_TENANT_NAME=${OS_TENANT_NAME}
      - OS_USERNAME=${OS_USERNAME}
      - OS_USER_DOMAIN_NAME=${OS_USER_DOMAIN_NAME}
      - PUBLICATIONS_DUMP_BUCKET=${PUBLICATIONS_DUMP_BUCKET}
      # Wiley
      - WILEY_PUBLICATION_URL=${WILEY_PUBLICATION_URL}
      - WILEY_TOKEN=${WILEY_TOKEN}
    depends_on:
      - redis
      - postgres
    restart: always


  web:
    build:
      context: .
      dockerfile: ./Dockerfiles/dev/Dockerfile
    volumes:
      - .:/src
    privileged: true
    ports:
      - "5004:5000"
    command: bash -c "sleep 10 && python3 manage.py run -h 0.0.0.0"
    environment:
      # Postgres database
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      # Elsevier
      - ELSEVIER_APIKEY=${ELSEVIER_APIKEY}
      - ELSEVIER_INSTTOKEN=${ELSEVIER_INSTTOKEN}
      - ELSEVIER_PUBLICATION_URL=${ELSEVIER_PUBLICATION_URL}
      # Swift
      - AUTH_VERSION=${AUTH_VERSION}
      - OS_AUTH_URL=${OS_AUTH_URL}
      - OS_PASSWORD=${OS_PASSWORD}
      - OS_PROJECT_DOMAIN_NAME=${OS_PROJECT_DOMAIN_NAME}
      - OS_PROJECT_ID=${OS_PROJECT_ID}
      - OS_PROJECT_NAME=${OS_PROJECT_NAME}
      - OS_REGION_NAME=${OS_REGION_NAME}
      - OS_TENANT_ID=${OS_TENANT_ID}
      - OS_TENANT_NAME=${OS_TENANT_NAME}
      - OS_USERNAME=${OS_USERNAME}
      - OS_USER_DOMAIN_NAME=${OS_USER_DOMAIN_NAME}
      - PUBLICATIONS_DUMP_BUCKET=${PUBLICATIONS_DUMP_BUCKET}
      # Wiley
      - WILEY_PUBLICATION_URL=${WILEY_PUBLICATION_URL}
      - WILEY_TOKEN=${WILEY_TOKEN}
    depends_on:
      - worker
    restart: always


volumes:
  bso3-harvest-publication:

