services:
  redis:
    image: redis:5.0.7-alpine
    ports:
      - "6379:6379"
  
  dashboard: 
    image: dataesr/dashboard-crawler:1.0
    ports:
      - "9181:9181"
    command: rq-dashboard -H redis
    depends_on:
      - redis

  worker:
    image: dataesr/bso3-harvest-publication:latest
    volumes:
      - bso3-harvest-publication:/src
    privileged: true
    command: python3 manage.py run_worker
    env_file:
      - .env
    depends_on:
      - redis

  web:
    image: dataesr/bso3-harvest-publication:latest
    privileged: true
    ports:
      - "5004:5000"
    command: python3 manage.py run -h 0.0.0.0
    env_file:
      - .env
    depends_on:
      - worker

volumes:
  bso3-harvest-publication:

