services:
  redis:
    image: redis:5.0.7-alpine
    networks:
      - bso-network

  dashboard:
    image: dataesr/dashboard-crawler:1.1
    ports:
      - 9181:9181
    command: rq-dashboard -H redis
    networks:
      - bso-network
    depends_on:
      - redis

  worker:
    build: .
    privileged: true
    command: >
        /bin/sh -c "python3 manage.py run_worker"
    environment:
      APP_SETTINGS: application.server.config.DevelopmentConfig
    networks:
      - bso-network
    depends_on:
      - redis

  web:
    build: .
    privileged: true
    ports:
      - 5004:5000
    command: python3 manage.py run -h 0.0.0.0
    environment:
      FLASK_DEBUG: 1
      APP_SETTINGS: application.server.config.DevelopmentConfig
    networks:
      - bso-network
    depends_on:
      - worker

networks:
  bso-network:
    driver: bridge
