
# General
TOKEN_KEY = 'TOKEN'
USER_KEY = 'USER'
PASS_KEY = 'PASS'

# Wiley
WILEY_KEY = 'WILEY'
EZPROXY_KEY = 'EZPROXY'
CONFIG_WILEY_TOKEN_KEY = f'{WILEY_KEY}_{TOKEN_KEY}'
CONFIG_WILEY_EZPROXY_USER_KEY = f'{WILEY_KEY}_{EZPROXY_KEY}_{USER_KEY}'
CONFIG_WILEY_EZPROXY_PASS_KEY = f'{WILEY_KEY}_{EZPROXY_KEY}_{PASS_KEY}'
CONFIG_WILEY_PUBLICATION_URL_KEY = f'{WILEY_KEY}_PUBLICATION_URL'
CONFIG_WILEY_BASE_URL_KEY = f'{WILEY_KEY}_BASE_URL'

# Database
DB_HARVESTED_STATUS_TABLE_NAME = "harvested_status_table"
DB_HARVESTING_DATE_COLUMN_NAME = "harvesting_date"
DB_DATASTET_VERSION_COLUMN_NAME = "datastet_version"

DB_MODEL_VERSION_INITIAL_VALUE = "0"
