# Wiley
WILEY = 'WILEY'
WILEY_TOKEN_KEY = f'{WILEY}_TOKEN'
WILEY_PUBLICATION_URL_KEY = f'{WILEY}_PUBLICATION_URL'

# Elsevier
ELSEVIER = 'ELSEVIER'
ELSEVIER_API_TOKEN_KEY = f'{ELSEVIER}_APIKEY'
ELSEVIER_INST_TOKEN_KEY = f'{ELSEVIER}_INSTTOKEN'
ELSEVIER_PUBLICATION_URL_KEY = f'{ELSEVIER}_PUBLICATION_URL'

# Database
DB_HARVESTED_STATUS_TABLE_NAME = "harvested_status_table"
DB_HARVESTING_DATE_COLUMN_NAME = "harvesting_date"
DB_DATASTET_VERSION_COLUMN_NAME = "datastet_version"

DB_MODEL_VERSION_INITIAL_VALUE = "0"
